version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    cooldown:
      default: 7
      default-days: 7
    groups:
      bun:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    cooldown:
      default: 7
      default-days: 7
    groups:
      gha:
        patterns:
          - "*"
