name: lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b
        with:
          activate-environment: true
          enable-cache: true

      # HACK: there's a bug in either `astral-sh/setup-uv` or pre-commit-uv or both
      # because uv gets installed to `/opt/hostedtoolcache/uv/<version>/x86_64/uv`
      # and pre-commit-uv apparently only looks for it at `~/.local/bin/uv`
      - run: |
          mkdir -p ~/.local/bin
          ln -sf $(which uv) ~/.local/bin/uv

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-1|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: |
          SKIP=no-commit-to-branch \
          uv run --with pre-commit-uv pre-commit run --all-files

  ts-changes:
    runs-on: ubuntu-24.04
    outputs:
      ts: ${{ steps.filter.outputs.ts }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            ts:
              - '.github/workflows/lint.yml'
              - 'src/**'
              - 'package.json'
              - 'bun.lock'
              - 'tsconfig.json'
              - 'biome.json'

  biome:
    runs-on: ubuntu-24.04
    needs: ts-changes
    if: needs.ts-changes.outputs.ts == 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run biome
        run: bun run lint

  typescript:
    runs-on: ubuntu-24.04
    needs: ts-changes
    if: needs.ts-changes.outputs.ts == 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run type checking
        run: bun run check-types
